/**
 * Signet Standard State Reader
 *
 * Reads signing requests from any conforming Compact contract's ledger state.
 * The MPC uses this to generically consume requests without knowing
 * the contract's application-specific fields.
 *
 * Works with the Ledger type generated by the Compact compiler.
 * Any contract that includes the signet standard fields will have
 * these fields in its Ledger type.
 */

import { decodeLengthPrefixed, decodeString } from './codec';
import { FIELD_NAMES } from './constants';
import { calldataArgKey } from './request-id';
import type { SigningRequest, EvmGasParams, CalldataFields } from './types';

/**
 * Minimal interface for a signet-conforming contract's ledger state.
 * Matches the shape generated by the Compact compiler for the standard fields.
 */
export interface SignetLedger {
  readonly mpcPubKeyHash: Uint8Array;
  readonly [FIELD_NAMES.nonce]: bigint;
  [FIELD_NAMES.requestNonce]: SignetMap<bigint>;
  // Calldata
  [FIELD_NAMES.calldataFuncSig]: SignetMap<Uint8Array>;
  [FIELD_NAMES.calldataArgCount]: SignetMap<bigint>;
  [FIELD_NAMES.calldataArgs]: SignetMap<Uint8Array>;
  // EVM params
  [FIELD_NAMES.evmTo]: SignetMap<Uint8Array>;
  [FIELD_NAMES.evmChainId]: SignetMap<bigint>;
  [FIELD_NAMES.evmNonce]: SignetMap<bigint>;
  [FIELD_NAMES.evmGasLimit]: SignetMap<bigint>;
  [FIELD_NAMES.evmMaxFee]: SignetMap<bigint>;
  [FIELD_NAMES.evmPriorityFee]: SignetMap<bigint>;
  [FIELD_NAMES.evmValue]: SignetMap<bigint>;
  // Routing
  [FIELD_NAMES.caip2Id]: SignetMap<Uint8Array>;
  [FIELD_NAMES.keyVersion]: SignetMap<bigint>;
  [FIELD_NAMES.path]: SignetMap<Uint8Array>;
  [FIELD_NAMES.algo]: SignetMap<Uint8Array>;
  [FIELD_NAMES.dest]: SignetMap<Uint8Array>;
  [FIELD_NAMES.params]: SignetMap<Uint8Array>;
  [FIELD_NAMES.outputSchema]: SignetMap<Uint8Array>;
  [FIELD_NAMES.respondSchema]: SignetMap<Uint8Array>;
  [FIELD_NAMES.outputData]: SignetMap<Uint8Array>;
}

/** Shape of a Compact Map in the generated Ledger type. */
export interface SignetMap<V> {
  isEmpty(): boolean;
  size(): bigint;
  member(key: Uint8Array): boolean;
  lookup(key: Uint8Array): V;
  [Symbol.iterator](): Iterator<[Uint8Array, V]>;
}

/**
 * Read calldata args from the dynamic arg array using compound keys.
 *
 * @param ledger The contract's ledger state
 * @param requestId The request ID
 * @param argCount Number of args to read
 * @returns Array of Bytes<32> arg values
 */
export function readCalldataArgs(
  ledger: SignetLedger,
  requestId: Uint8Array,
  argCount: number,
): Uint8Array[] {
  const args: Uint8Array[] = [];
  for (let i = 0; i < argCount; i++) {
    const key = calldataArgKey(requestId, i);
    if (!ledger[FIELD_NAMES.calldataArgs].member(key)) {
      throw new Error(`Calldata arg ${i} not found for request ${Buffer.from(requestId).toString('hex')}`);
    }
    args.push(ledger[FIELD_NAMES.calldataArgs].lookup(key));
  }
  return args;
}

/**
 * Read a single signing request from the ledger by its request ID (map key).
 *
 * @param ledger The contract's ledger state (from the indexer)
 * @param requestId The request ID (Bytes<32> map key)
 * @param predecessor The contract address (ContractCall.address)
 * @returns The decoded SigningRequest, or null if the request doesn't exist
 */
export function readRequest(
  ledger: SignetLedger,
  requestId: Uint8Array,
  predecessor: string,
): SigningRequest | null {
  if (!ledger[FIELD_NAMES.requestNonce].member(requestId)) {
    return null;
  }

  // Read calldata
  const funcSigRaw = ledger[FIELD_NAMES.calldataFuncSig].lookup(requestId);
  const argCount = Number(ledger[FIELD_NAMES.calldataArgCount].lookup(requestId));
  const args = readCalldataArgs(ledger, requestId, argCount);

  // Decode function signature — stored with pad(256, ...) which is null-terminated, not length-prefixed
  // pad() in Compact left-pads a string into a Bytes<N>. We need to decode it.
  const funcSig = decodePaddedString(funcSigRaw);

  const calldata: CalldataFields = {
    funcSig,
    argCount,
    args,
  };

  // Read EVM params
  const evmParams: EvmGasParams = {
    evmTo: ledger[FIELD_NAMES.evmTo].lookup(requestId),
    evmChainId: ledger[FIELD_NAMES.evmChainId].lookup(requestId),
    evmNonce: ledger[FIELD_NAMES.evmNonce].lookup(requestId),
    evmGasLimit: ledger[FIELD_NAMES.evmGasLimit].lookup(requestId),
    evmMaxFee: ledger[FIELD_NAMES.evmMaxFee].lookup(requestId),
    evmPriorityFee: ledger[FIELD_NAMES.evmPriorityFee].lookup(requestId),
    evmValue: ledger[FIELD_NAMES.evmValue].lookup(requestId),
  };

  return {
    predecessor,
    requestId,
    nonce: ledger[FIELD_NAMES.requestNonce].lookup(requestId),
    evmParams,
    calldata,
    caip2Id: decodeString(ledger[FIELD_NAMES.caip2Id].lookup(requestId)),
    keyVersion: Number(ledger[FIELD_NAMES.keyVersion].lookup(requestId)),
    path: new Uint8Array(ledger[FIELD_NAMES.path].lookup(requestId)),
    algo: decodeString(ledger[FIELD_NAMES.algo].lookup(requestId)),
    dest: decodeString(ledger[FIELD_NAMES.dest].lookup(requestId)),
    params: decodeLengthPrefixed(ledger[FIELD_NAMES.params].lookup(requestId)),
    outputDeserializationSchema: decodeLengthPrefixed(ledger[FIELD_NAMES.outputSchema].lookup(requestId)),
    respondSerializationSchema: decodeLengthPrefixed(ledger[FIELD_NAMES.respondSchema].lookup(requestId)),
  };
}

/**
 * Read ALL pending signing requests from a contract's ledger.
 * Iterates the signetRequestNonce map to discover all request IDs,
 * then reads each request's full data.
 *
 * @param ledger The contract's ledger state
 * @param predecessor The contract address
 * @returns Array of all pending signing requests
 */
export function readAllRequests(
  ledger: SignetLedger,
  predecessor: string,
): SigningRequest[] {
  const requests: SigningRequest[] = [];
  for (const [requestId] of ledger[FIELD_NAMES.requestNonce]) {
    // Skip requests that already have outputData (already claimed)
    if (ledger[FIELD_NAMES.outputData].member(requestId)) continue;
    const req = readRequest(ledger, requestId, predecessor);
    if (req) requests.push(req);
  }
  return requests;
}

/**
 * Check if a contract's ledger contains the mpcPubKeyHash matching the MPC's own public key hash.
 * Used for dynamic contract discovery in the block stream.
 */
export function matchesMpcPubKeyHash(
  ledger: SignetLedger,
  mpcPubKeyHash: Uint8Array,
): boolean {
  if (!ledger.mpcPubKeyHash) return false;
  if (ledger.mpcPubKeyHash.length !== mpcPubKeyHash.length) return false;
  for (let i = 0; i < mpcPubKeyHash.length; i++) {
    if (ledger.mpcPubKeyHash[i] !== mpcPubKeyHash[i]) return false;
  }
  return true;
}

/**
 * Decode a Compact pad(N, "string") value.
 * pad() writes the UTF-8 bytes starting at index 0 and zero-fills the rest.
 * We read until the first null byte (or end of buffer).
 */
function decodePaddedString(bytes: Uint8Array): string {
  let end = bytes.length;
  for (let i = 0; i < bytes.length; i++) {
    if (bytes[i] === 0) {
      end = i;
      break;
    }
  }
  return new TextDecoder().decode(bytes.slice(0, end));
}
