name: CI Tests

on:
  workflow_run:
    workflows: ['Publish Docker Image']
    types: [completed]
    branches: [main]
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'pull_request' }}
    container:
      image: ghcr.io/${{ github.repository }}/signet-anchor-build-env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env:
      MPC_ROOT_KEY: ${{ secrets.MPC_ROOT_KEY }}
      INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Build fakenet-signer
        working-directory: clients/response-server
        run: yarn build

      - name: Run lint
        working-directory: signet-program
        run: yarn run lint

      - name: Run format check
        working-directory: signet-program
        run: yarn run format:check

      - name: Generate keypair
        run: solana-keygen new --no-bip39-passphrase --force

      - name: Set Solana private key
        run: |
          SOLANA_PRIVATE_KEY=$(cat ~/.config/solana/id.json)
          echo "SOLANA_PRIVATE_KEY=$SOLANA_PRIVATE_KEY" >> $GITHUB_ENV

      - name: Run Anchor tests
        working-directory: signet-program
        run: |
          anchor --version
          anchor test

      - name: Run type check
        working-directory: signet-program
        run: yarn run typecheck
