name: CI Tests

on:
  push:
    paths:
      - "signet-program/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "signet-program/**"
      - ".github/workflows/**"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/solana-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env:
      PRIVATE_KEY_TESTNET: 0x0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: signet-program
        run: yarn install

      - name: Run lint
        working-directory: signet-program
        run: yarn run lint

      - name: Run format check
        working-directory: signet-program
        run: yarn run format:check

      - name: Run type check
        working-directory: signet-program
        run: yarn run typecheck

      - name: Generate keypair
        run: solana-keygen new --no-bip39-passphrase --force

      - name: Run Anchor tests
        working-directory: signet-program
        run: anchor test
