name: CI

on:
  push:
    paths:
      - "signet-program/**"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "signet-program/**"
      - ".github/workflows/ci.yml"

jobs:
  ci:
    name: Lint/Format/Typecheck + Anchor tests
    runs-on: ubuntu-24.04
    env:
      PRIVATE_KEY_TESTNET: 0x0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install JS deps
        working-directory: signet-program
        run: yarn install

      - name: Lint
        working-directory: signet-program
        run: yarn run lint

      - name: Install Rust (rustup)
        shell: bash
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source "$HOME/.cargo/env"

      - name: Add Cargo to PATH
        shell: bash
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install Solana CLI (Anza)
        shell: bash
        run: curl -sSfL https://release.anza.xyz/stable/install | sh

      - name: Add Solana to PATH
        shell: bash
        run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Install Anchor build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev libudev-dev build-essential libclang-dev

      - name: Install Anchor CLI
        run: |
          source "$HOME/.cargo/env"
          cargo install --git https://github.com/coral-xyz/anchor --tag v0.31.1 anchor-cli --locked
          echo "Anchor version:"
          anchor --version

      - name: Generate Solana keypair
        run: |
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          solana-keygen new --no-bip39-passphrase --force

      - name: Anchor tests
        working-directory: signet-program
        run: |
          source "$HOME/.cargo/env"
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          which anchor || (echo "Anchor not found!" && exit 1)
          anchor test
