name: CI

on:
  push:
    branches: [main, develop, 'feature/**', 'felipe/**']
  pull_request:
    branches: [main, develop]

env:
  SOLANA_VERSION: 1.18.17
  ANCHOR_VERSION: 0.31.0
  NODE_VERSION: 20

jobs:
  lint-format-typecheck:
    name: Lint, Format & Typecheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm install -g yarn

      - uses: dtolnay/rust-toolchain@stable

      - uses: metadaoproject/setup-solana@v1.0
        with:
          solana-cli-version: ${{ env.SOLANA_VERSION }}

      - uses: metadaoproject/setup-anchor@v1.2
        with:
          anchor-version: ${{ env.ANCHOR_VERSION }}

      - run: yarn install --frozen-lockfile
        working-directory: ./signet-program

      - run: anchor build
        working-directory: ./signet-program

      - run: yarn check
        working-directory: ./signet-program

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm install -g yarn

      - uses: dtolnay/rust-toolchain@stable

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: metadaoproject/setup-solana@v1.0
        with:
          solana-cli-version: ${{ env.SOLANA_VERSION }}

      - uses: metadaoproject/setup-anchor@v1.2
        with:
          anchor-version: ${{ env.ANCHOR_VERSION }}

      - run: yarn install --frozen-lockfile
        working-directory: ./signet-program

      - run: anchor test
        working-directory: ./signet-program

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: metadaoproject/setup-solana@v1.0
        with:
          solana-cli-version: ${{ env.SOLANA_VERSION }}

      - uses: metadaoproject/setup-anchor@v1.2
        with:
          anchor-version: ${{ env.ANCHOR_VERSION }}

      - run: anchor build
        working-directory: ./signet-program

      - run: test -f target/deploy/chain_signatures.so && test -f target/deploy/proxy_test_cpi.so
        working-directory: ./signet-program