name: CI

on:
  push:
    paths:
      - "signet-program/**"
      - ".github/workflows/ci.yml"
      - "Dockerfile"
  pull_request:
    paths:
      - "signet-program/**"
      - ".github/workflows/ci.yml"
      - "Dockerfile"

jobs:
  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}/solana-ci:${{ github.sha }}
            ghcr.io/${{ github.repository }}/solana-ci:latest

  test:
    name: Lint/Format/Typecheck + Anchor tests
    needs: build-docker
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY_TESTNET: 0x0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.repository }}/solana-ci:${{ github.sha }}

      - name: Run CI tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace/signet-program \
            -e PRIVATE_KEY_TESTNET="${PRIVATE_KEY_TESTNET}" \
            ghcr.io/${{ github.repository }}/solana-ci:${{ github.sha }} \
            bash -c "
              set -e
              echo '=== Installing dependencies ==='
              yarn install

              echo '=== Running lint ==='
              yarn run lint

              echo '=== Running format check ==='
              yarn run format:check

              echo '=== Running type check ==='
              yarn run typecheck

              echo '=== Generating keypair ==='
              solana-keygen new --no-bip39-passphrase --force

              echo '=== Running Anchor tests ==='
              anchor test
            "