name: CI

on:
  push:
    branches: [main, develop, 'feature/**', 'felipe/**']
  pull_request:
    branches: [main, develop]

env:
  SOLANA_VERSION: 1.18.17
  ANCHOR_VERSION: 0.31.0
  NODE_VERSION: 20
  RUST_VERSION: stable

# Security: Restrict permissions
permissions:
  contents: read
  pull-requests: read

jobs:
  lint-format-typecheck:
    name: Lint, Format & Typecheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Cache yarn
        uses: actions/cache@v4
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - run: npm install -g yarn

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt, clippy

      - name: Cache Solana binaries
        uses: actions/cache@v4
        id: solana-cache
        with:
          path: |
            ~/.cache/solana
            ~/.local/share/solana
          key: ${{ runner.os }}-solana-${{ env.SOLANA_VERSION }}

      - name: Install Solana CLI
        if: steps.solana-cache.outputs.cache-hit != 'true'
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install)"

      - name: Setup Solana PATH
        run: echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Cache Anchor binary
        uses: actions/cache@v4
        id: anchor-cache
        with:
          path: ~/.cargo/bin/anchor
          key: ${{ runner.os }}-anchor-${{ env.ANCHOR_VERSION }}

      - name: Install Anchor CLI
        if: steps.anchor-cache.outputs.cache-hit != 'true'
        run: |
          cargo install --git https://github.com/coral-xyz/anchor --tag v${{ env.ANCHOR_VERSION }} anchor-cli --locked

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - run: yarn install --frozen-lockfile
        working-directory: ./signet-program

      - run: anchor build
        working-directory: ./signet-program

      - run: yarn check
        working-directory: ./signet-program

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Cache yarn
        uses: actions/cache@v4
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - run: npm install -g yarn

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-test-
            ${{ runner.os }}-cargo-

      - name: Cache Solana binaries
        uses: actions/cache@v4
        id: solana-cache
        with:
          path: |
            ~/.cache/solana
            ~/.local/share/solana
          key: ${{ runner.os }}-solana-${{ env.SOLANA_VERSION }}

      - name: Install Solana CLI
        if: steps.solana-cache.outputs.cache-hit != 'true'
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install)"

      - name: Setup Solana PATH
        run: echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Cache Anchor binary
        uses: actions/cache@v4
        id: anchor-cache
        with:
          path: ~/.cargo/bin/anchor
          key: ${{ runner.os }}-anchor-${{ env.ANCHOR_VERSION }}

      - name: Install Anchor CLI
        if: steps.anchor-cache.outputs.cache-hit != 'true'
        run: |
          cargo install --git https://github.com/coral-xyz/anchor --tag v${{ env.ANCHOR_VERSION }} anchor-cli --locked

      - run: yarn install --frozen-lockfile
        working-directory: ./signet-program

      - name: Generate test keypair
        run: solana-keygen new --no-bip39-passphrase --force
        working-directory: ./signet-program

      - run: anchor test
        working-directory: ./signet-program

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-
            ${{ runner.os }}-cargo-

      - name: Cache Solana binaries
        uses: actions/cache@v4
        id: solana-cache
        with:
          path: |
            ~/.cache/solana
            ~/.local/share/solana
          key: ${{ runner.os }}-solana-${{ env.SOLANA_VERSION }}

      - name: Install Solana CLI
        if: steps.solana-cache.outputs.cache-hit != 'true'
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install)"

      - name: Setup Solana PATH
        run: echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Cache Anchor binary
        uses: actions/cache@v4
        id: anchor-cache
        with:
          path: ~/.cargo/bin/anchor
          key: ${{ runner.os }}-anchor-${{ env.ANCHOR_VERSION }}

      - name: Install Anchor CLI
        if: steps.anchor-cache.outputs.cache-hit != 'true'
        run: |
          cargo install --git https://github.com/coral-xyz/anchor --tag v${{ env.ANCHOR_VERSION }} anchor-cli --locked

      - run: anchor build
        working-directory: ./signet-program

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: programs
          path: ./signet-program/target/deploy/
          retention-days: 7