name: Publish Docker Image

on:
  push:
    branches: [main]
    paths:
      - "Dockerfile"
  pull_request:
    paths:
      - "Dockerfile"
  workflow_dispatch:

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}/signet-anchor-build-env:latest
            ghcr.io/${{ github.repository }}/signet-anchor-build-env:main
            ghcr.io/${{ github.repository }}/signet-anchor-build-env:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
